INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (1, FALSE, 3, 'Diutamakan yang pernah saya ajar', '3528031202');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (1, FALSE, 3, '', '4047893854');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (2, FALSE, 9, '', '3611263342');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (2, FALSE, 2, '', '4144885032');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (3, FALSE, 1, '', '4421663062');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (3, FALSE, 9, 'Diutamakan tidak mendaftar asdos MK lain', '4777381851');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (4, FALSE, 6, '', '3035652810');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (4, FALSE, 9, 'Nilai B silahkan ikut daftar', '4477276074');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (5, FALSE, 8, '', '4217097164');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (5, FALSE, 6, 'Diutamakan yang pernah saya ajar', '4744624053');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (6, FALSE, 6, '', '4043896614');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (6, FALSE, 5, '', '4385499191');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (7, FALSE, 3, '', '3528031202');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (7, FALSE, 10, '', '3995859523');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (11, FALSE, 10, '', '4289432766');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (11, FALSE, 8, 'Nilai B silahkan ikut daftar', '4325533101');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (12, FALSE, 7, '', '4237037878');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (12, FALSE, 3, 'Nilai B silahkan ikut daftar', '3365718295');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (13, FALSE, 6, '', '3122804230');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (13, FALSE, 1, '', '4047893854');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (14, FALSE, 1, '', '3122804230');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (14, FALSE, 9, 'Nilai B silahkan ikut daftar', '3549817534');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (15, FALSE, 3, '', '3472342523');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (15, FALSE, 10, '', '4809912594');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (16, FALSE, 4, '', '3365718295');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (16, FALSE, 9, 'Diutamakan tidak mendaftar asdos MK lain', '3472342523');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (17, FALSE, 1, '', '3739982678');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (17, FALSE, 7, '', '3215261901');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (21, FALSE, 9, 'Diutamakan tidak mendaftar asdos MK lain', '3672861132');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (21, FALSE, 8, '', '3995859523');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (22, FALSE, 3, 'Nilai B silahkan ikut daftar', '4124707564');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (22, FALSE, 2, '', '4043896614');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (23, FALSE, 2, 'Minimal IPK 3.00', '4595228326');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (23, FALSE, 5, '', '4385499191');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (24, FALSE, 3, '', '4746900794');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (24, FALSE, 2, '', '4769663945');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (25, FALSE, 7, '', '3045894452');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (25, FALSE, 4, 'Minimal IPK 3.00', '4368065352');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (26, FALSE, 3, 'Nilai B silahkan ikut daftar', '3035652810');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (26, FALSE, 8, '', '3340836167');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (27, FALSE, 8, 'Diutamakan tidak mendaftar asdos MK lain', '3496267033');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (27, FALSE, 1, '', '3215261901');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (28, FALSE, 4, 'Diutamakan yang pernah saya ajar', '3937455565');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (28, FALSE, 1, '', '4064403590');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (29, FALSE, 5, '', '4421663062');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (29, FALSE, 7, '', '4289432766');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (30, FALSE, 6, '', '4064403590');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (30, FALSE, 5, 'Nilai B silahkan ikut daftar', '3549817534');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (31, FALSE, 3, 'Diutamakan tidak mendaftar asdos MK lain', '4368065352');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (31, FALSE, 10, '', '4261865704');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (35, FALSE, 7, 'Diutamakan tidak mendaftar asdos MK lain', '4325533101');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (35, TRUE, 3, '', '3672861132');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (36, FALSE, 10, '', '4015060337');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (36, TRUE, 6, 'Minimal IPK 3.00', '3059038648');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (37, FALSE, 7, 'Diutamakan tidak mendaftar asdos MK lain', '3177272910');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (37, TRUE, 8, '', '4860234283');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (38, FALSE, 10, '', '3937455565');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (38, TRUE, 1, 'Diutamakan yang pernah saya ajar', '4144885032');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (39, TRUE, 3, '', '4983146928');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (39, TRUE, 3, 'Nilai B silahkan ikut daftar', '3059038648');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (46, FALSE, 7, 'Diutamakan tidak mendaftar asdos MK lain', '4595228326');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (47, FALSE, 6, '', '4777381851');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (48, FALSE, 6, 'Nilai B silahkan ikut daftar', '3215261901');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (49, FALSE, 9, 'Minimal IPK 3.00', '4144885032');
INSERT INTO LOWONGAN (idkelasmk, status, jumlah_asisten, syarat_tambahan, nipdosenpembuka) VALUES (50, FALSE, 6, 'Diutamakan tidak mendaftar asdos MK lain', '4015060337');