INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSCE604121', 'Game Development', NULL);
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSCM603127', 'Rekayasa Pereangkat Lunak', 'CSCE604121');
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSCE604131', 'Jejaring Semantik', NULL);
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSGE602022', 'Perancangan & Pemrograman Web', 'CSCE604131');
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSCE604132', 'Komputasi Lunak', NULL);
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSCM603130', 'Sistem Cerdas', 'CSCE604132');
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSCE604134', 'Pengolahan Multimedia', NULL);
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSCE604133', 'Pengolahan Citra', 'CSCE604134');
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSCE604150', 'Organisasi Sistem Komputer', NULL);
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSCM601252', 'Pengantar Organisasi Komputer', 'CSCE604150');
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSCM601150', 'Pengantar Sistem Dijital', 'CSCM601252');
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSCE604174', 'Basis Data Lanjut', NULL);
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSGE602070', 'Basis Data', 'CSCE604174');
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSGE602040', 'Struktur Data & Algoritma', 'CSGE602070');
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSGE601021', 'Dasar-Dasar Pemrograman 2', 'CSGE602040');
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSGE601020', 'Dasar-Dasar Pemrograman 1', 'CSGE601021');
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSCE604212', 'Persamaan Diferensial', NULL);
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSCM602115', 'Matematika Dasar 2', 'CSCE604212');
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('UIST601014', 'Matematika Dasar 1', 'CSCM602115');
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSGE601011', 'Matematika Diskret 2', NULL);
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSGE601010', 'Matematika Diskret 1', 'CSGE601011');
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSCE604231', 'Pengolahan Bahasa Manusia', NULL);
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSCE604135', 'Perolehan Informasi', 'CSCE604231');
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSCE604232', 'Robotika', NULL);
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSCE604253', 'Rancangan Sistem Dijital', 'CSCE604232');
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSCM603154', 'Jaringan Komputer', NULL);
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSGE602055', 'Sistem Operasi', 'CSCM603154');
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSIE604274', 'Administrasi Sistem', NULL);
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSIM602160', 'Administrasi Bisnis', 'CSIE604274');
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSIM603189', 'Manajemen Proyek TI', NULL);
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSIM602161', 'Prinsip-prinsip Manajemen', 'CSIM603189');
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSIM604182', 'Manajemen SI', NULL);
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSIM601280', 'Prinsip-prinsip SI', 'CSIM604182');
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSGE603291', 'Metodologi Penelitian & Penulisan Ilmiah', NULL);
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSIM603026', 'Pemrograman Skala Perusahaan', NULL);
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSGE602012', 'Aljabar Linier', NULL);
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSCE604130', 'Bioinformatika', NULL);
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSCE604233', 'Data Mining', NULL);
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSCE604241', 'Grafika Komputer', NULL);
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSGE604098', 'Kerja Praktik', NULL);
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSGE614093', 'Komputer & Masyarakat', NULL);
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSIE604266', 'Konfigurasi ERP', NULL);
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSCE604243', 'Kriptografi & Keamanan Informasi', NULL);
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSCE604271', 'Layanan & Aplikasi Web', NULL);
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSCE604225', 'Metode Formal', NULL);
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSCE604235', 'Pemelajaran Mesin', NULL);
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSCE604143', 'Pemodelan Geometris', NULL);
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSCM602023', 'Pemrograman Lanjut', NULL);
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSCE604222', 'Pemrograman Logika', NULL);
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSCM603128', 'Pemrograman Sistem', NULL);
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSCE604152', 'Pengolahan Sinyal Dijital', NULL);
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSCM603228', 'Proyek Perangkat Lunak', NULL);
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSCE604111', 'Simulasi & Pemodelan', NULL);
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSIM603124', 'Sistem Interaksi', NULL);
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSCE604154', 'Sistem Terdistribusi', NULL);
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSGE602013', 'Statistika dan Probabilitas', NULL);
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSCE604228', 'Teknik Kompilator', NULL);
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSCE604179', 'Teknologi Mobile', NULL);
INSERT INTO MATA_KULIAH (kode, nama, prasyarat_dari) VALUES ('CSCM602241', 'Teori Bahasa & Automata', NULL);